jobs:
- job: runHudiTestSuite
  pool: # we run the end to end tests on the msft hosted agents
    vmImage: 'ubuntu-latest'
  steps:
    - script: ./hudi-test-suite/prepare_integration_suite.sh
      displayName: Build
